### PR TITLE
prashant-initialCommit

### PR DESCRIPTION
**Pull request by 04vibs**

### CODE REVIEW

**Comment by jdecode** [comment]
@04vibs - I see package-lock.json without package.json
Can you please confirm if this is correct?
I was expecting either both (package + lock) or none.

**Comment by sarabs3** [comment]
Thank you for the PR. 

@04vibs please remove package-lock.json file from the commit

**Review by sarabs3 — CHANGES_REQUESTED** [review]
Remove package-lock.json file from the commit.

**Review by sarabs3 — APPROVED** [review]
Thanks for the PR. I'm going to merge it now.

**Pull request merged**
